version: '3'

networks:
  todo-network:
    driver: bridge

services:
  postgres:
    image: 'postgres:15'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=todo'
      - 'POSTGRES_USER=todo'
    ports:
      - "5432:5432"
    container_name: "todo-app-postgres-15"
    networks:
      - todo-network

  todo-app:
    build: .
    ports:
      - "9090:9090"
    container_name: "todo-app-0.0.1"
    networks:
      - todo-network
