name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 20  # Use the version compatible with your Spring Boot project

    - name: Build with Gradle
      run: ./gradlew build

    - name: Start PostgreSQL container
      run: |
        docker run --name postgres:15 -e POSTGRES_USER=todo -e POSTGRES_PASSWORD=todo -p 5432:5432 -d postgres
        sleep 5  # Give PostgreSQL some time to start

    - name: Run Tests
      run: ./gradlew test

    - name: Stop PostgreSQL container
      run: |
        docker stop postgres
        docker rm postgres

