name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: 'gradle'
        check-latest: true

    - name: Build with Gradle
      run: ./gradlew build

    - name: Start PostgreSQL container
      run: |
        docker run --name postgres -e POSTGRES_USER=todo -e POSTGRES_PASSWORD=todo -p 5432:5432 -d postgres:15
        sleep 5

    - name: Run Tests
      run: ./gradlew test

    - name: Stop PostgreSQL container
      run: |
        docker stop postgres
        docker rm postgres

